version: '3.8'

services:
  stats-server:
    build:
      context: ./stats
      args:
        SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm-stats
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
    image: stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres
    container_name: stats-db
    environment:
      POSTGRES_DB: ewm-stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./stats/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/postgresql/data